### PR TITLE
Crash fix and other improvements

### PR DESCRIPTION
**Pull request by adib**
- Fixed crashing when the text view's contents is set programmatically.
- Applied the MIT license to source files
- Use the system font's size as a base for the text view's font
  - next-up is to respond to text style changes
- Cache regex objects to improve performance a bit

### CODE REVIEW

**Comment by ruddfawcett** [comment]
Whoops, sorry I completely missed this... I'll take a look when I can.

**Comment by ruddfawcett** [comment]
Sorry - completely forgot about this.  A lot of this looks good.  One concern I do have is the updated toolbar -- I think that it is a little too much, and maybe we should go back to the original one.

Also, multi-line code highlighting seems to have broken...

```
this doesn't work anymore...
```

Any suggestions?

**Comment by adib** [comment]
@ruddfawcett The toolbar buttons originally came from @landakram's branch which seems to be more maintained.

**Comment by adib** [comment]
@ruddfawcett Code formatting was done in 590d9340874029a81e6cda8f6db72831a01ca3cb

**Comment by landakram** [comment]
@adib @ruddfawcett, ugh, yes, once upon a time @ruddfawcett reached out to me about cleaning up my branch and merging it in, but I haven't had the time. 

Sorry for making this difficult here!

**Comment by ruddfawcett** [comment]
@adib I see you've still been working on this with a few updates -- would you like me to add you as a collaborator to the repository? Might be easier for you, and while I no longer use this library in my apps, it would benefit the general public to have your changes. Thoughts?

**Comment by ruddfawcett** [comment]
Hello all, RFMarkdownTextView has been deprecated. As a replacement, I just released [Notepad](https://github.com/ruddfawcett/Notepad) (based on RFMarkdownTextView), a new Swift 3.0 Markdown editor. Notepad is faster, fully themeable, and more extensible as a library. Be sure to check it out.

**Pull request closed without merging**
